### ISSUE TITLE
Lower experimental results

### ISSUE THREAD

**Issue by zhou07** [Show-han/PET-Reconstruction#10]
Thank you for sharing your code; it's excellent work. However, I encountered a discrepancy when I used your dataset and checkpoint to obtain results.  Running inference.py produced a folder named 'results', and then executing our_paper_metric.py yielded experimental results for PSNR, SSIM, and NMSE according to the 'results' folder. They were lower than those reported in your paper, as depicted in the image provided. Is this process correct?
![result1](https://github.com/Show-han/PET-Reconstruction/assets/32354174/ceedd69e-66d4-4ab2-a452-c1f73859e9cb)

Additionally, I encountered an error while running our_paper_metric.py, which seemed to originate from the following line of code. 
`cur_ssim = ssim(SPETimg, EPETimg, multi_channel=1)`
`ValueError: Since image dtype is floating point, you must specify the data_range parameter. Please read the documentation carefully (including the note). It is recommended that you always specify the data_range anyway.`
After modifying that line, I was able to run our_paper_metric.py successfully.
`cur_ssim = ssim(SPETimg, EPETimg, multi_channel=1, data_range=dr)`

**Comment by wyhlovecpp** [comment]
I think you can download ITK-SNAP to check the visualization. And you need to make sure you've loaded the [checkpoint](https://github.com/Show-han/PET-Reconstruction/blob/18bd4a5cda514e5b7d0bd745af51e78aae166991/config/sr_sr3_16_128.json#L12) correctly and check that the [timesteps](https://github.com/Show-han/PET-Reconstruction/blob/18bd4a5cda514e5b7d0bd745af51e78aae166991/config/sr_sr3_16_128.json#L84) and other hyperparameters are consistent. 

The error in ssim calculation is related to the version of skimage, which we will correct.

**Comment by Koid217** [comment]
I have met the same questions, but the difference is that I started training from 0, and finally ran a result similar to psnr=21.
