### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yransun** [Show-han/PET-Reconstruction#15]
Dear author,

I am trying to do some experiments on the data you mentioned Ultra-low Dose PET Imaging Challenge 2022. Do you know where I can download the dataset? seems like their challenge website is down.

Thanks for your time!

**Comment by Show-han** [comment]
Thank you for reaching out. The dataset used in our paper was obtained through an application process, and I’m not sure about its current availability or sharing permissions. Since I’m uncertain about the copyright and usage rights, I’m unable to provide the download link directly.
