### ISSUE TITLE
a question about data preparation

### ISSUE THREAD

**Issue by escwall** [Show-han/PET-Reconstruction#2]
great implementation~however, may i ask about how do you preprocess the dataset? Thx

**Comment by wyhlovecpp** [comment]
Thank you for your question. Our data processing approach begins by segmenting the entire dataset of human PET scans into 128x128x128 3D slices, focusing on the central head region. These 3D slices are then normalized and further divided into 128 2D slices along the z-axis (transverse plane). We will soon provide our processed data and checkpoints.

**Comment by escwall** [comment]
Thanks for your reply! I appreciate it if you guys could provide processed data, checkpoints and latest code :)👍

**Comment by Show-han** [comment]
We have released the data and checkpoints.

**Comment by zhizhuo716** [comment]
May i ask what software you use to segment the dataset

**Comment by wyhlovecpp** [comment]
> May i ask what software you use to segment the dataset
We use the Python code library SimpleITK to process PET images. The original processing code is missing, so I rewrote a manual processing code and uploaded it to the directory ’./data/dataprocess.py‘

**Comment by wyhlovecpp** [comment]
> May i ask what software you use to segment the dataset

We use the Python code library SimpleITK to segment PET images. The original processing code is missing, so I rewrote a manual processing code and uploaded it to the directory ’./data/dataprocess.py‘.
