### ISSUE TITLE
Training code issue

### ISSUE THREAD

**Issue by wangpengbo31348** [Show-han/PET-Reconstruction#4]
Training code has issues. After using your uploaded train dataset, the following error occurred：
/model/model.py", line 99, in optimize_parameters
    l_pix = (l_pix.sum())/int(b*c*h*w)+loss_guide
             ^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'sum'

**Comment by wyhlovecpp** [comment]
Thanks for your question. There is a small mistake about return type. We have modified [this line](https://github.com/Show-han/PET-Reconstruction/blob/55cd3d69ee7eea34caf00f39a3a9eb69a81ac2ce/model/model.py#L96) in our code.
