### ISSUE TITLE
about the average indicator value

### ISSUE THREAD

**Issue by Koid217** [Show-han/PET-Reconstruction#7]
Great job. I have a small question. I used the checkpoint you gave and calculated the indicators in inference. I found that the average value of psnr was 30.32, ssim was 0.93, and nmse was 0.034. They are different from the values in the paper. What is wrong with me?

**Comment by wyhlovecpp** [comment]
Maybe you only use the inference.py to eval metric.  It‘s just a reference.  This file ["our_paper_metric.py"](https://github.com/Show-han/PET-Reconstruction/blob/18bd4a5cda514e5b7d0bd745af51e78aae166991/our_paper_metric.py) will help you.
