### ISSUE TITLE
About the experimental results

### ISSUE THREAD

**Issue by ZSH0824** [Show-han/PET-Reconstruction#9]
The output of the experimental results is the section diagram of SPET in the first place and the section diagram of EPET in the second place. However, I can't find what EPET refers to from the paper. I would be very grateful if you could give me an answer.

**Comment by wyhlovecpp** [comment]
Maybe EPET is estimated PET. This is a placeholder name in the code used to store the final result of our model, unrelated to the paper.

**Comment by ZSH0824** [comment]
![image_0](https://github.com/Show-han/PET-Reconstruction/assets/122593605/cadd2c8f-b7cc-4b5c-ae03-bc4a36a17ad9)

Thank you very much for your timely answer, and I have one more question. After visualizing the experimental results, I found that the experimental results labeled SPET were not the standard dose PET images I imagined, but more like the predicted residual after IRM processing. I don't know if this is a problem in my debugging process.

**Comment by wyhlovecpp** [comment]
You can see [here](https://github.com/Show-han/PET-Reconstruction/blob/18bd4a5cda514e5b7d0bd745af51e78aae166991/model/model.py#L176) for more details. out_dict['IP'] is CPM result, out_dict['SR'] is IRM result, out_dict['INF'] is input low dose pet, out_dict['HR'] is standard dose pet. 

I think you visualize [this](https://github.com/Show-han/PET-Reconstruction/blob/18bd4a5cda514e5b7d0bd745af51e78aae166991/inference.py#L86) as SPET. This row is indeed the result of the residual prediction which is the result of our IRM prediction
